[mypy]

[mypy-pandas]
ignore_missing_imports = True

[mypy-matplotlib]
ignore_missing_imports = True

[mypy-matplotlib.pyplot]
ignore_missing_imports = True

[mypy-geopandas]
ignore_missing_imports = True
